server:
  port: 9001

spring:
  application:
    name: eureka-client1
eureka:
  instance:
    ip-address: localhost
    prefer-ip-address: true
    appname: eureka-client1
  client:
    register-with-eureka: true
    fetch-registry: true
    region: CN
    service-url:
      defaultZone: http://localhost:8761/eureka/
