server:
  port: 8763
spring:
  application:
    name: eureka-server
  mvc:
    favicon:
      enabled: false
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server-dist-1:8761/eureka/,http://eureka-server-dist-2:8762/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    ip-address: localhost
    hostname: eureka-server-dist-3