server:
  port: 8070

spring:
  application:
    name: eureka-auth-server-1
eureka:
  instance:
    ip-address: localhost
    prefer-ip-address: true
    appname: eureka-auth-server
  client:
    register-with-eureka: true
    fetch-registry: true
    region: CN
    service-url:
      defaultZone: http://localhost:8761/eureka/
