server:
  port: 9003

spring:
  application:
    name: eureka-ribbon-client
eureka:
  instance:
    ip-address: localhost
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
